[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Danylo Petrakivskyi", email = "danylopetrik@gmail.com"},
]
dependencies = [
    "scipy>=1.9.3",
    "ipython>=8.14.0",
]
requires-python = ">=3.10"
license = {text = "GPL-3.0-or-later"}
